# Generated by Django 4.2.29 on 2026-05-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(choices=[('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], max_length=20, verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['niveau', 'nom_classe'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('matiere', models.CharField(max_length=100, verbose_name='Matière enseignée')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100, verbose_name='Destination (Ville)')),
                ('date_sortie', models.DateField(verbose_name='Date de la sortie')),
                ('nb_eleves', models.PositiveIntegerField(verbose_name="Nombre d'élèves")),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorties.classe', verbose_name='Classe participante')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorties.enseignant', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Sortie scolaire',
                'verbose_name_plural': 'Sorties scolaires',
                'ordering': ['date_sortie'],
            },
        ),
    ]
